version: "3"

volumes:
  ckan_storage:
  pg_data:
  solr_data:

services:
  ckan:
    container_name: ckan
    image: ckan/ckan-base:2.9.5
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "0.0.0.0:5000:5000" 
    volumes:
      - ckan_storage:/var/lib/ckan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:5000"]

  db:
    container_name: db
    image: postgres:12-alpine
    environment:
      - DATASTORE_READONLY_PASSWORD=datastore
      - POSTGRES_PASSWORD=ckan
      - PGDATA=/var/lib/postgresql/data/db
      - POSTGRES_USER=ckan
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ckan"]

  solr:
    container_name: solr
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    container_name: redis
    image: redis:6
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
