---
version: 2

jobs:
  build:
    docker:
      - image: udata/circleci:2-alpine
      - image: mongo:3.6
      - image: redis:alpine
      - image: udata/elasticsearch:2.4.5
      - image: postgres:11-alpine
        name: db
        environment:
          POSTGRES_DB: ckan
          POSTGRES_USER: ckan
          POSTGRES_PASSWORD: ckan
          DS_RO_PASS: datastore
        # https://discuss.circleci.com/t/cant-run-sql-file-against-docker-for-setup/14166/4
      - image: ckan/solr:latest
        name: solr
      - image: ckan/ckan-base:2.9.5
        environment:
          CKAN_SQLALCHEMY_URL: postgresql://ckan:ckan@db/ckan
          CKAN_DATASTORE_WRITE_URL: postgresql://ckan:ckan@db/datastore
          CKAN_DATASTORE_READ_URL: postgresql://datastore_ro:datastore@db/datastore
          CKAN_SOLR_URL: http://solr:8983/solr/ckan
          CKAN_REDIS_URL: redis://localhost:6379/1
          CKAN_DATAPUSHER_URL: http://datapusher:8800
          CKAN_SITE_URL: http://localhost:5000
          CKAN_MAX_UPLOAD_SIZE_MB: 50
          CKAN_WAIT_FOR: tcp://db:5432
          POSTGRES_PASSWORD: ckan
          DS_RO_PASS: datastore
    environment:
       BASH_ENV: /root/.bashrc
    steps:
      - checkout
      - run:
          name: Prepare postgres
          command: |
            apt-get update && sudo apt-get install postgresql
            psql < postgresql/docker-entrypoint-initdb.d/10_create_datastore.sql
      - run:
          name: Compute Python dependencies key
          command: cat requirements/*.pip > python.deps
      - run:
          name: Get the base reference branch
          command: export BASE_BRANCH=$(base_branch)
      - restore_cache:
          keys:
          - py-cache-v6-{{ arch }}-{{ checksum "python.deps" }}
          - py-cache-v6-{{ arch }}-{{ .Branch }}
          - py-cache-v6-{{ arch }}-{{ .Environment.BASE_BRANCH }}
      - run:
          name: Install python dependencies
          command: |
            virtualenv venv
            source venv/bin/activate
            pip install -e . || pip install -e .
            pip install -r requirements/develop.pip || pip install -r requirements/develop.pip
      - save_cache:
          key: py-cache-v6-{{ arch }}-{{ checksum "python.deps" }}
          paths:
          - venv
      - save_cache:
          key: py-cache-v6-{{ arch }}-{{ .Branch }}
          paths:
          - venv
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            inv qa test --report
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
          destination: reports
      - run:
          name: Build a distributable package
          command: |
            source venv/bin/activate
            # Build a wheel release
            if [[ $CIRCLE_TAG ]]; then
                # This is a tagged release
                inv dist
            elif [[ "$CIRCLE_BRANCH" == feature/* ]]; then
                # This is a feature branch
                inv dist -b $CIRCLE_BUILD_NUM+${CIRCLE_BRANCH#*/}
            else
                # This is a simple development build
                inv dist -b $CIRCLE_BUILD_NUM
            fi
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - venv

  publish:
    docker:
      - image: udata/circleci:2-alpine
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Publish on PyPI
          command: |
            source venv/bin/activate
            pip install twine
            twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/*.whl

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          context: org-global
